apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threetier-app
  namespace: argocd
spec:
  project: myproj
  source:
    repoURL: https://github.com/amitopenwriteup/threetieracrossns.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
