---
# Sync Wave 0: PersistentVolume (created first)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-wordpress
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/wordpress
---
# Sync Wave 1: PersistentVolumeClaim (created after PV)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wb-pvc
  namespace: wordpress
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
