---
# Sync Wave 0: PersistentVolume (created first)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  local:
    path: /mnt/data/database
---
# Sync Wave 1: PersistentVolumeClaim (created after PV)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
